all : report.pdf problem-statement.pdf

report.pdf :
	pdflatex report.ltx

problem-statement.pdf :
	pdflatex problem-statement.ltx

requirements.pdf :
	pdflatex requirements.ltx

techreview.pdf :
	pdflatex techreview.ltx
