all :
	pdflatex report.ltx

project-statement.pdf :
	pdflatex project-statement.ltx

clean :
	rm -f report.aux report.log report.out report.pdf
	rm -f project-statement.aux project-statement.log project-statement.out project-statement.pdf
